// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA6OM_qiiFyEGuJjrP5yj9orfvf0GSqHA',
    appId: '1:500504012249:web:6fd79dd2009a975622e5c8',
    messagingSenderId: '500504012249',
    projectId: 'sponsorenlauf-evp-wetzikon',
    authDomain: 'sponsorenlauf-evp-wetzikon.firebaseapp.com',
    storageBucket: 'sponsorenlauf-evp-wetzikon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR0mIc4N5w-Tip4OBlgteYbGCerx7whrg',
    appId: '1:500504012249:android:a465489bf418541f22e5c8',
    messagingSenderId: '500504012249',
    projectId: 'sponsorenlauf-evp-wetzikon',
    storageBucket: 'sponsorenlauf-evp-wetzikon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzCDAYNE90FcBNGFRiYLDh7cjK7Q9OnkM',
    appId: '1:500504012249:ios:7b6746f9be0e2dfa22e5c8',
    messagingSenderId: '500504012249',
    projectId: 'sponsorenlauf-evp-wetzikon',
    storageBucket: 'sponsorenlauf-evp-wetzikon.firebasestorage.app',
    iosClientId: '500504012249-9oh0v3mt1ctiuqr5u7jogldo0hjqbi6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.sponsorenlaufApp',
  );

}