name: Flutter CI

on:
  push:
  pull_request:

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze (non-fatal infos/warnings)
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      # Tests sind optional – schlagen nicht fehl, falls keine vorhanden
      - name: Test
        run: flutter test -r compact || true
