name: Flutter CI

on:
  push:
  pull_request:

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      # Falls aktuell noch keine Tests vorhanden sind, schlägt dieser Schritt nicht fehl.
      - name: Test
        run: flutter test -r compact || true
